"use client";

import { useEffect, useState } from "react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { doc, getDoc } from "firebase/firestore";
import { auth, db } from "@/lib/firebase";
import { useRouter } from "next/navigation";

export default function StaffDashboard(){const router=useRouter();const[name,setName]=useState("Staff");const[role,setRole]=useState("");const[checking,setChecking]=useState(true);useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){router.replace("/staff/login");return;}const s=await getDoc(doc(db,"adminUsers",u.uid));const d=s.data();if(!s.exists()||d?.active!==true||!["admin","supporter"].includes(d?.role)){await signOut(auth);router.replace("/staff/login");return;}setName(d.displayName||u.displayName||"Staff");setRole(d.role);setChecking(false);}),[router]);if(checking)return <main className="flex min-h-screen items-center justify-center"><p className="font-bold text-violet-700">Securing Staff Portal...</p></main>;return <main className="min-h-screen bg-[#f7f5ff]"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl justify-between px-5 py-4"><div><p className="text-xs font-black uppercase tracking-widest text-violet-600">Staff Portal</p><h1 className="text-2xl font-black">EduJAMB</h1></div><button onClick={async()=>{await signOut(auth);router.replace("/staff/login")}} className="rounded-xl border px-4 py-2 text-sm font-bold">Sign out</button></div></header><section className="mx-auto max-w-6xl px-5 py-10"><h2 className="text-3xl font-black">Welcome, {name}</h2><p className="mt-2 text-gray-500">Role: <span className="font-bold text-violet-700">{role}</span></p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{["Content Management","Student Support","Reports","Academic Resources","Community Moderation","Notifications"].map(x=><div key={x} className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-black">{x}</h3><p className="mt-2 text-sm text-gray-500">Access will be controlled by role as each platform module is implemented.</p></div>)}</div></section></main>}
